#define CHECK_INTERVAL 30000
#define SEND_INTERVAL 300000
#define ANALOG_TEMPERATURE_PIN 0
#define WIFI_RX 2
#define WIFI_TX 3
#define CSV_BUFFER_SIZE 64

//#define DEBUG_RAM
//#define SET_TIME

#define _ESPLOGLEVEL_ 3
